### ISSUE TITLE
Add server metrics and aggregated data

### ISSUE THREAD

**Issue by blockchainluffy** [shutter-network/encrypting-rpc-server#38]
We'd like to add several metrics to the ERPC server:

This particular issue is about adding server related metrics:
- Server uptime
- Server load
- Error rate
- Memory usage
- Aggregate data in form of histograms: request count, request duration, encryption duration, and requested gas limit

Other metrics will be collected as part of:
- https://github.com/shutter-network/encrypting-rpc-server/issues/39
- https://github.com/shutter-network/encrypting-rpc-server/issues/40

**Comment by ylembachar** [comment]
We probably want to divide the metrics into two separate parts: 

**Server Usage Metrics:** uptime, load, error rate, memory usage, restart rate, number of requests.

**Transaction Metrics:** Number of transactions in the cache, for each transaction: the incoming transaction hash, the encrypted transaction hash, the inclusion time and the number of retries but this needs a better specification.

@ulope anything else we should add/update? is this what you had in mind with regards to the rpc metrics?

**Comment by blockchainluffy** [comment]
>   for each transaction: the incoming transaction hash, the encrypted transaction hash
I think, using prometheus metrics for this is a bit tricky as we cannot use different labels for different transactions. It could increase memory usage very much. Similarly for, inclusion time and number of retries, we cannot divide these based on each transaction. I am open to suggestions here, as how should we implement it? @ulope @ylembachar

**Comment by ylembachar** [comment]
My suggestion would be to store these in a separate database that we can then query via Grafana. We could create a dashboard that gives us a view on the latest transactions that were processed in the encrypting rpc. The table would include the link between the incoming transaction hash, the encrypted transaction hash, the submission time, the inclusion time, and the number of retries and this would give us an idea of the transaction lifecycle from the encrypting RPC side but let's perhaps discuss whether this is any different from the observer transaction lifecycle during the daily.

**Comment by blockchainluffy** [comment]
Created two issues

- https://github.com/shutter-network/encrypting-rpc-server/issues/39
- https://github.com/shutter-network/encrypting-rpc-server/issues/40
